"""Adds url to leads

Revision ID: 1babd7376a8b
Revises: e106239a3986
Create Date: 2021-02-26 02:45:49.565417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1babd7376a8b'
down_revision = 'e106239a3986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('url', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'url')
    # ### end Alembic commands ###
