"""initial

Revision ID: 4f9ec9b76f32
Revises: 
Create Date: 2021-01-06 18:07:24.868456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f9ec9b76f32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('reference', sa.String(length=100), nullable=True))
    op.alter_column('leads', 'position',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.add_column('stages', sa.Column('reference', sa.String(length=100), nullable=True))
    op.alter_column('stages', 'end_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('stages', 'start_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stages', 'start_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('stages', 'end_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('stages', 'reference')
    op.alter_column('leads', 'position',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_column('leads', 'reference')
    # ### end Alembic commands ###
