"""Adds public_id

Revision ID: 5a0ed82e90ca
Revises: ff965a5b7ee8
Create Date: 2021-01-28 05:52:45.443028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a0ed82e90ca'
down_revision = 'ff965a5b7ee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('public_id', sa.String(length=32), nullable=False))
    op.create_unique_constraint('uq_lead_public_id', 'leads', ['public_id'])
    op.add_column('stages', sa.Column('public_id', sa.String(length=32), nullable=False))
    op.create_unique_constraint('uq_stage_public_id', 'stages', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stages', 'public_id')
    op.drop_column('leads', 'public_id')
    # ### end Alembic commands ###
