"""Renames position to role

Revision ID: 798ea0a04eeb
Revises: 5a0ed82e90ca
Create Date: 2021-01-29 16:50:32.707344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '798ea0a04eeb'
down_revision = '5a0ed82e90ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('leads', sa.Column('role', sa.String(length=100), nullable=False))
    # op.drop_column('leads', 'position')
    # op.alter_column('leads', 'position', sa.String(length=100), nullable=False),
    # ### end Alembic commands ###

    op.alter_column(
        'leads',
        column_name = 'position',
        new_column_name = 'role',
        existing_type = sa.String(100),
        existing_nullable = False,
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'leads',
        column_name = 'role',
        new_column_name = 'position',
        existing_type = sa.String(100),
        existing_nullable = False,
    )
    # ### end Alembic commands ###
