"""empty message

Revision ID: a7448f374890
Revises: ff965a5b7ee8
Create Date: 2021-01-26 18:14:26.997834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7448f374890'
down_revision = 'ff965a5b7ee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('public_id', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'leads', ['public_id'])
    op.add_column('stages', sa.Column('public_id', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'stages', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stages', type_='unique')
    op.drop_column('stages', 'public_id')
    op.drop_constraint(None, 'leads', type_='unique')
    op.drop_column('leads', 'public_id')
    # ### end Alembic commands ###
